### ISSUE TITLE
As IDEM I want traffic from the app proxy to be routed via a HTTP proxy with a static IP so that exchanges can whitelist

### ISSUE THREAD

**Issue by xcjlo985** [dltxio/proxy.idem.com.au#33]
See the [architecture diagram](https://github.com/dltxio/proxy.idem.com.au/pull/32) for how this looks. Effort required will be:
1. Setup a DO droplet with bog standard HTTPs proxy software
2. Assign a static/reserved IP to the droplet
3. Configure proxy.idem.com.au to route all *outbound* traffic via the new HTTPS proxy
4. Document and notify stakeholders what the IP address

Test plan
* End to end test outbound proxy.idem.com.au and verify all traffic is routed via the HTTPs proxy on the reserved IP address

Testing steps
- ssh into `idem-proxy-server` on DO
- ran `tail -f /var/log/squid/access.log`
- sending request to exchange
- the request should be routed via proxy server and showing up in access.log

**Comment by xcjlo985** [comment]
Possibly helpful:
* https://docs.digitalocean.com/products/networking/reserved-ips/how-to/outbound-traffic/
* https://www.digitalocean.com/community/tutorials/how-to-set-up-squid-proxy-on-ubuntu-22-04

**Comment by C00p3rb123** [comment]
Unable to send requests - because of #352 (not able to verify mobile)

**Comment by C00p3rb123** [comment]
please move back to testing once bug is resolved
