### ISSUE TITLE
As IDEM I want better endpoint error handling so I know what is going wrong with my requests

### ISSUE THREAD

**Issue by pondpiu** [dltxio/proxy.idem.com.au#44]
All different vendors have different success and error responses when sending request to vendor endpoint. Update the reponses.

GPIB:

```
Error 401 

{ "Invalid signature" }

Error 400
{ "Email and password are required" }

{ "Invalid email" }

{ "This email is already in use" }
```

Digital surge:

Update the post request with the below data:
```
{
   “first_name”: “first_name”,
   “last_name”: “last_name”,
   “email”: [test@test.com](mailto:test@test.com),
   “phone_number”: “[+614499111011](tel:+614499111011)”
}
Responses
Token returned is temporary read, write token valid for 1 hour
200 OK
{
   “token”: “<temp partner token for customer>“,
   “password”: “<temp password>”
}
Error 400
Existing username or email found
{
   “message”: “Unable to create customer”
}
Validation error example
{
   “first_name”: [“This field is required.“]
}
```

**Comment by C00p3rb123** [comment]
Blocked by #352 - can not verify mobile number

**Comment by C00p3rb123** [comment]
Blocked by multiple exchange sign up issues which are currently being worked on by @xiangzhe0812

**Comment by C00p3rb123** [comment]
Testing/Demo Steps:

**Mobile**

- Sign up to GPIB with an invalid email address 
- Sign up to GPIB with an email already in use
- Sign up to Digital Surge with an email already in use

**Postman**

- Send a request without an email and password in the body
- Send a request with an invalid signature
- Send a request to digital surge without a first name
