### ISSUE TITLE
As IDEM, I want to make the format and naming of the endpoints consistent, so I'm following best practice

### ISSUE THREAD

**Issue by Mitchell139** [dltxio/proxy.idem.com.au#56]
Given - a developer looking to integrate with the IDEM proxy
When - the developer loads the IDEM proxy swagger site to view the api docs
Then - the developer should see api routes that have consistent naming and style conventions applied

https://uat-proxy.idem.com.au/swagger
![image](https://user-images.githubusercontent.com/50130291/187366978-d9b1e152-e16d-42d5-857f-b84d0a19f83f.png)

**Comment by xcjlo985** [comment]
@TomDodson do we know if there will be changes to the routes/endpoints based on the new UI redesign discussions?

**Comment by xcjlo985** [comment]
@xiangzhe0812 as discussed:

- change /user -> /health
- change all /user to /users as entities should be plural
- change POST /users to POST /users/create
- change all camelCase paths to hyphens (camelCase is fine in variables)
- change POST /user/verifyOtp to POST /otp/verify
- change POST /user/requestOtp to GET /otp/request
- remove POST /user/tester
- remove POST /user/syncDetail
- change POST /user/signup to POST /exchange/signup
- change POST /user/signup/notification to /exchange/signup/callback
- change POST /user/notification/{message} to POST /users/notify (message in body)
- change PUT /user/{userId}/token to PUT /users/{userId} (token already in body, change to expoToken)
- change POST /user/verify to POST /verify-claims

Alex to review use of primary identifier for the user object. Currently there is a mix of email, hashed-email and userId.
This needs a refactor to make it consistent.

**Comment by C00p3rb123** [comment]
change POST /user/requestOtp to GET /otp/request - **currently still POST**
change POST /user/signup to POST /exchange/signup - **currently POST /exchanges/signup**
change POST /user/signup/notification to /exchange/signup/callback - **currently POST /exchanges/signup/callback **
change POST /user/notification/{message} to POST /users/notify (message in body) - **currently POST /users/notification**
change POST /user/verify to POST /verify-claims **currently POST users/verify**

**Comment by xiangzhe0812** [comment]
@C00p3rb123 
change POST /user/signup to POST /exchange/signup - currently POST /exchanges/signup
change POST /user/signup/notification to /exchange/signup/callback - currently POST /exchanges/signup/callback
Should be exchagnes, I updated the ticket

I will update rest of the end point from your comment

**Comment by Mitchell139** [comment]
change POST /user/verify to POST /verify-claims - currently POST users/verify-claims
