### ISSUE TITLE
As IDEM Proxy I want to POST users documents to greenID so we can verify users

### ISSUE THREAD

**Issue by TomDodson** [dltxio/proxy.idem.com.au#59]
To post to the Proxy a user has all of the required claims and document metadata. Required documents are determined by GreenID matrix. We are starting with the row that does not require the address claim or documents that contain addresses to be KYC'd by GreenID.

**Addresses are not mandatory**

### AC1
- Given I receive the required claims and document metadata from the app (Required claims and documents specified in #)
- When I POST these claims and document metadata in a single payload to GreenID
- Then the user will be registered in GreenID and the document metadata will be DVS checked

### AC2
- Given I have received a "Verified" response
- When I sign the claims with the WC3 schema
- Then I will return the signed claims to the user's device

### AC3
- If I have received any other response other than verified
- Then post back to the apple with the error code "Error, please contract support"

### Test steps:
In the app 
1. add Drivers licence and Medicare card documents (set licence number to 11111111 and medicare card number to 2111111111)
2. set up pgp
3. make a fullname and DOB claim and attach drivers license and medicare cards.
4. press Verify My Claims.
5. wait to finish verification
6. got to https://test-au.vixverify.com/admin-login/customers/dltx_labs/login.seam and log in with dltx account
7. click search and you should see your details as the latest customer
![image](https://user-images.githubusercontent.com/21031310/192937677-af0a3a7d-c150-4969-ae7d-6266e752abd3.png)

**Comment by amagon270** [comment]
Done but the claim is being signed with a PGP key not with the etherium address.

**Comment by C00p3rb123** [comment]
After clicking verify my claims button an alert is returned without a title

**Comment by xiangzhe0812** [comment]
@amagon270 @C00p3rb123  fixed on IDEM-434

**Comment by Mitchell139** [comment]
Cooper forgot to say that we also needed to change the message.
