### ISSUE TITLE
As IDEM I want to have a Xero service so that I can have invoices automatically generated

### ISSUE THREAD

**Issue by jinggg-y** [dltxio/proxy.idem.com.au#67]
## AC
- Given the proxy invoice endpoint receives a valid token and vendor id = 1 (GPIB)
- The xero service will assemble an invoice that contains all the KYC instances found in the IDEM db for GPIB
- The service will then submit the invoice to Xero as a draft
- The invoice is able to found under Business > Invoices > Draft

## Test steps
- Get a new auth token from the `Request Xero Token` endpoint on hoppsotch.io
- Put the new token in the body of the invoice endpoint request (`Send Invoices` on hoppsotch)
- Put the number of the vendor you want to invoice in the body of the request (the number can be found in the `VendorEnum` type in the [repo](https://github.com/dltxio/proxy.idem.com.au/blob/9695346a37d70563fc7d9419edb2b0a794f91a52/src/interfaces.ts#L38))
- If the invoices are successfully sent, it will return "Invoices sent"
- If there is an error, it will return an error
- Should the invoices be sent, they will be found in Xero's demo company under Business > Invoices > Draft
- Verify the date is correct, the amount of items are correct, and the vendor being billed is correct

**Comment by brettvniekerk** [comment]
Note: process has changed to send invoice to given Vendor, not all of them at once

**Comment by Mitchell139** [comment]
@brettvniekerk Can you please add test steps and update the AC as required so it's up to date please

**Comment by brettvniekerk** [comment]
@Mitchell139 how's the AC and TS?

**Comment by Mitchell139** [comment]
Followed instructions and this is what I get
![image](https://user-images.githubusercontent.com/50130291/188796507-980cd8a5-8457-48dc-9804-d5275b34c521.png)

```
{
  "statusCode": 500,
  "message": "{\"response\":{\"statusCode\":403,\"body\":{\"Type\":null,\"Title\":\"Forbidden\",\"Status\":403,\"Detail\":\"AuthenticationUnsuccessful\",\"Instance\":\"24d92869-957d-4bf7-ac7b-7520c55388fe\",\"Extensions\":{}},\"headers\":{\"content-type\":\"application/json\",\"content-length\":\"150\",\"server\":\"nginx\",\"xero-correlation-id\":\"24d92869-957d-4bf7-ac7b-7520c55388fe\",\"x-appminlimit-remaining\":\"9999\",\"expires\":\"Wed, 07 Sep 2022 05:29:30 GMT\",\"cache-control\":\"max-age=0, no-cache, no-store\",\"pragma\":\"no-cache\",\"date\":\"Wed, 07 Sep 2022 05:29:30 GMT\",\"connection\":\"close\",\"x-client-tls-ver\":\"tls1.3\"},\"request\":{\"uri\":{\"protocol\":\"https:\",\"slashes\":true,\"auth\":null,\"host\":\"api.xero.com\",\"port\":443,\"hostname\":\"api.xero.com\",\"hash\":null,\"search\":null,\"query\":null,\"pathname\":\"/api.xro/2.0/Invoices\",\"path\":\"/api.xro/2.0/Invoices\",\"href\":\"https://api.xero.com/api.xro/2.0/Invoices\"},\"method\":\"PUT\",\"headers\":{\"user-agent\":\"xero-node-4.26.0\",\"xero-tenant-id\":\"\",\"Authorization\":\"Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjFDQUY4RTY2NzcyRDZEQzAyOEQ2NzI2RkQwMjYxNTgxNTcwRUZDMTkiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJISy1PWm5jdGJjQW8xbkp2MENZVmdWY09fQmsifQ.eyJuYmYiOjE2NjI1Mjg0OTIsImV4cCI6MTY2MjUzMDI5MiwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS54ZXJvLmNvbSIsImF1ZCI6Imh0dHBzOi8vaWRlbnRpdHkueGVyby5jb20vcmVzb3VyY2VzIiwiY2xpZW50X2lkIjoiODczQzY4M0QwQ0E1NDI4RjhEQjEyRTFEMENDMjQxODUiLCJzdWIiOiI4NTdmMmZiZTllYzU1MTZmYWY5NjQ0MWIxMzkxMzE1ZiIsImF1dGhfdGltZSI6MTY2MjUyODE1MiwieGVyb191c2VyaWQiOiJiNDYzMTMwZS02MmRmLTRmNWYtODQ3NS1kMTNhNjRkMDhlMWQiLCJnbG9iYWxfc2Vzc2lvbl9pZCI6ImYwNzIzNGNhYWNmZTRlNjdiOTgwMDAxOTJlYjcwYzc1IiwianRpIjoiMjIwMmE0NWE5ZWIzZmJhNDUxMTQwYWQ0N2VhNDY0MTUiLCJhdXRoZW50aWNhdGlvbl9ldmVudF9pZCI6IjYwN2E0Y2YyLTIzMTgtNDZlNC05ZThiLWE2ZDE2ZmQ2ODdjMSIsInNjb3BlIjpbImVtYWlsIiwicHJvZmlsZSIsIm9wZW5pZCIsImFjY291bnRpbmcudHJhbnNhY3Rpb25zIiwiYWNjb3VudGluZy5jb250YWN0cyIsIm9mZmxpbmVfYWNjZXNzIl0sImFtciI6WyJwd2QiXX0.OwVPVDUNeFTBaoDF9-rclOPDIkfpbXCndgv2h9QpTUX24f9_0eukd2Z3xnmoFTL-0I1SDJCNyfTUl5hdzKr_vD6eA0fB3wAw-_jixpSvIT6DBZjvPiMY5hP23GiCQBfakbxsJHx0y4M260kQSiSwXeQKopd89kQzi7hVbxGnpiVsuAbDeH0Y8_Dqb732aDZfiZDYVh47yDRvSjEQpDf3GaNpq0F5fGp-nf1PM2x8X19WKCFJ4xmKpllCv9MzWB5Oe3jldJBQGEzunNvtyDSDw0bcEJPaeD1CXivusWbd8-_rcGhloIDeM8mrGRLRbKS7Ye0gmyDxHQQ0PYcIr9OgJQ\",\"accept\":\"application/json\",\"content-type\":\"application/json\",\"content-length\":194,\"x-datadog-trace-id\":\"2083073104741278785\",\"x-datadog-parent-id\":\"8721620030445895011\",\"x-datadog-sampling-priority\":\"1\"}}},\"body\":{}}"
}
```

**Comment by brettvniekerk** [comment]
> Followed instructions and this is what I get ![image](https://user-images.githubusercontent.com/50130291/188796507-980cd8a5-8457-48dc-9804-d5275b34c521.png)
> 
> ```
> {
>   "statusCode": 500,
>   "message": "{\"response\":{\"statusCode\":403,\"body\":{\"Type\":null,\"Title\":\"Forbidden\",\"Status\":403,\"Detail\":\"AuthenticationUnsuccessful\",\"Instance\":\"24d92869-957d-4bf7-ac7b-7520c55388fe\",\"Extensions\":{}},\"headers\":{\"content-type\":\"application/json\",\"content-length\":\"150\",\"server\":\"nginx\",\"xero-correlation-id\":\"24d92869-957d-4bf7-ac7b-7520c55388fe\",\"x-appminlimit-remaining\":\"9999\",\"expires\":\"Wed, 07 Sep 2022 05:29:30 GMT\",\"cache-control\":\"max-age=0, no-cache, no-store\",\"pragma\":\"no-cache\",\"date\":\"Wed, 07 Sep 2022 05:29:30 GMT\",\"connection\":\"close\",\"x-client-tls-ver\":\"tls1.3\"},\"request\":{\"uri\":{\"protocol\":\"https:\",\"slashes\":true,\"auth\":null,\"host\":\"api.xero.com\",\"port\":443,\"hostname\":\"api.xero.com\",\"hash\":null,\"search\":null,\"query\":null,\"pathname\":\"/api.xro/2.0/Invoices\",\"path\":\"/api.xro/2.0/Invoices\",\"href\":\"https://api.xero.com/api.xro/2.0/Invoices\"},\"method\":\"PUT\",\"headers\":{\"user-agent\":\"xero-node-4.26.0\",\"xero-tenant-id\":\"\",\"Authorization\":\"Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjFDQUY4RTY2NzcyRDZEQzAyOEQ2NzI2RkQwMjYxNTgxNTcwRUZDMTkiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJISy1PWm5jdGJjQW8xbkp2MENZVmdWY09fQmsifQ.eyJuYmYiOjE2NjI1Mjg0OTIsImV4cCI6MTY2MjUzMDI5MiwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS54ZXJvLmNvbSIsImF1ZCI6Imh0dHBzOi8vaWRlbnRpdHkueGVyby5jb20vcmVzb3VyY2VzIiwiY2xpZW50X2lkIjoiODczQzY4M0QwQ0E1NDI4RjhEQjEyRTFEMENDMjQxODUiLCJzdWIiOiI4NTdmMmZiZTllYzU1MTZmYWY5NjQ0MWIxMzkxMzE1ZiIsImF1dGhfdGltZSI6MTY2MjUyODE1MiwieGVyb191c2VyaWQiOiJiNDYzMTMwZS02MmRmLTRmNWYtODQ3NS1kMTNhNjRkMDhlMWQiLCJnbG9iYWxfc2Vzc2lvbl9pZCI6ImYwNzIzNGNhYWNmZTRlNjdiOTgwMDAxOTJlYjcwYzc1IiwianRpIjoiMjIwMmE0NWE5ZWIzZmJhNDUxMTQwYWQ0N2VhNDY0MTUiLCJhdXRoZW50aWNhdGlvbl9ldmVudF9pZCI6IjYwN2E0Y2YyLTIzMTgtNDZlNC05ZThiLWE2ZDE2ZmQ2ODdjMSIsInNjb3BlIjpbImVtYWlsIiwicHJvZmlsZSIsIm9wZW5pZCIsImFjY291bnRpbmcudHJhbnNhY3Rpb25zIiwiYWNjb3VudGluZy5jb250YWN0cyIsIm9mZmxpbmVfYWNjZXNzIl0sImFtciI6WyJwd2QiXX0.OwVPVDUNeFTBaoDF9-rclOPDIkfpbXCndgv2h9QpTUX24f9_0eukd2Z3xnmoFTL-0I1SDJCNyfTUl5hdzKr_vD6eA0fB3wAw-_jixpSvIT6DBZjvPiMY5hP23GiCQBfakbxsJHx0y4M260kQSiSwXeQKopd89kQzi7hVbxGnpiVsuAbDeH0Y8_Dqb732aDZfiZDYVh47yDRvSjEQpDf3GaNpq0F5fGp-nf1PM2x8X19WKCFJ4xmKpllCv9MzWB5Oe3jldJBQGEzunNvtyDSDw0bcEJPaeD1CXivusWbd8-_rcGhloIDeM8mrGRLRbKS7Ye0gmyDxHQQ0PYcIr9OgJQ\",\"accept\":\"application/json\",\"content-type\":\"application/json\",\"content-length\":194,\"x-datadog-trace-id\":\"2083073104741278785\",\"x-datadog-parent-id\":\"8721620030445895011\",\"x-datadog-sampling-priority\":\"1\"}}},\"body\":{}}"
> }
> ```

u didnt put in the vendor id

**Comment by brettvniekerk** [comment]
Configured DO env vars, so should be gtg

**Comment by C00p3rb123** [comment]
This link will be helpful for the demo: 

https://github.com/dltxio/proxy.idem.com.au#xero
