### ISSUE TITLE
As IDEM I want to have a test app in Xero so that I can test invoicing clients without causing costs

### ISSUE THREAD

**Issue by jinggg-y** [dltxio/proxy.idem.com.au#69]

**Comment by OptimusOpus** [comment]
![image](https://user-images.githubusercontent.com/34178563/188562510-0ddd0bb7-07d0-4fe8-aa52-be61764fb575.png)

**Comment by Mitchell139** [comment]
@OptimusOpus What Xero account and organisation are we using?

**Comment by OptimusOpus** [comment]
The xero account is the dev@dltx.io one in bitwarden. The organisation for the moment is Demo company
